# Site settings
title: Make Your Own Predictor
email: kashiwabara@utfpr.edu.br 
description: > # this means to ignore newlines until "baseurl:"
  MYOP is a flexible gene finding system  that facilitates the experimentation and comparison of new probabilistic gene modelling.
baseurl: "" 
url: "http://myopdev.github.io" # the base hostname & protocol for your site
twitter_username:  ayoshiaki
github_username:  ayoshiaki

# Build settings
markdown: kramdown
